name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --force

      - name: Create environment file
        run: |
          echo "export const environment = {" > src/environments/environment.prod.ts
          echo "  production: true," >> src/environments/environment.prod.ts
          echo "  apiUrl: '${{ secrets.API_URL }}'," >> src/environments/environment.prod.ts
          echo "};" >> src/environments/environment.prod.ts

      - name: Build
        run: npm run build -- --configuration production --base-href "/${{ github.event.repository.name }}/"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/app-trips
          branch: gh-pages
